---
name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run bats tests
      run: docker run -t -v "${PWD}:/code" bats/bats:latest test/*.bats
  test-stack:
    strategy:
      matrix:
        stack: [heroku-18, heroku-20, heroku-22]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run stack test
      run: bash test/test-stack.sh ${{ matrix.stack }}
